language: cpp
compiler: clang
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxml2-dev
  - sudo apt install libglew-dev libglfw3-dev libglm-dev libgl1-mesa-dev xorg-dev clang
script:
- make